/* eslint quotes: ["error", "double"] */

let osisList = [
  {"id": "Gen", "name": "Genesis", "testament": "O", "start": "gen"},
  {"id": "Exod", "name": "Exodus", "testament": "O", "start": "exo"},
  {"id": "Lev", "name": "Leviticus", "testament": "O", "start": "lev"},
  {"id": "Num", "name": "Numbers", "testament": "O", "start": "num"},
  {"id": "Deut", "name": "Deuteronomy", "testament": "O", "start": "deu"},
  {"id": "Josh", "name": "Joshua", "testament": "O", "start": "jos"},
  {"id": "Judg", "name": "Judges", "testament": "O", "start": "judg"},
  {"id": "Ruth", "name": "Ruth", "testament": "O", "start": "rut"},
  {"id": "1Sam", "name": "1 Samuel", "testament": "O", "start": "1sa"},
  {"id": "2Sam", "name": "2 Samuel", "testament": "O", "start": "2sa"},
  {"id": "1Kgs", "name": "1 Kings", "testament": "O", "start": "1ki"},
  {"id": "2Kgs", "name": "2 Kings", "testament": "O", "start": "2ki"},
  {"id": "1Chr", "name": "1 Chronicles", "testament": "O", "start": "1ch"},
  {"id": "2Chr", "name": "2 Chronicles", "testament": "O", "start": "2ch"},
  {"id": "Ezra", "name": "Ezra", "testament": "O", "start": "ezr"},
  {"id": "Neh", "name": "Nehemiah", "testament": "O", "start": "neh"},
  {"id": "Esth", "name": "Esther", "testament": "O", "start": "est"},
  {"id": "Job", "name": "Job", "testament": "O", "start": "job"},
  {"id": "Ps", "name": "Psalms", "testament": "O", "start": "psa"},
  {"id": "Prov", "name": "Proverbs", "testament": "O", "start": "pro"},
  {"id": "Eccl", "name": "Ecclesiastes", "testament": "O", "start": "ecc"},
  {"id": "Song", "name": "Song of Solomon", "testament": "O", "start": "son"},
  {"id": "Isa", "name": "Isaiah", "testament": "O", "start": "isa"},
  {"id": "Jer", "name": "Jeremiah", "testament": "O", "start": "jer"},
  {"id": "Lam", "name": "Lamentations", "testament": "O", "start": "lam"},
  {"id": "Ezek", "name": "Ezekiel", "testament": "O", "start": "eze"},
  {"id": "Dan", "name": "Daniel", "testament": "O", "start": "dan"},
  {"id": "Hos", "name": "Hosea", "testament": "O", "start": "hos"},
  {"id": "Joel", "name": "Joel", "testament": "O", "start": "joe"},
  {"id": "Amos", "name": "Amos", "testament": "O", "start": "amo"},
  {"id": "Obad", "name": "Obadiah", "testament": "O", "start": "oba"},
  {"id": "Jonah", "name": "Jonah", "testament": "O", "start": "jon"},
  {"id": "Mic", "name": "Micah", "testament": "O", "start": "mic"},
  {"id": "Nah", "name": "Nahum", "testament": "O", "start": "nah"},
  {"id": "Hab", "name": "Habakkuk", "testament": "O", "start": "hab"},
  {"id": "Zeph", "name": "Zephaniah", "testament": "O", "start": "zep"},
  {"id": "Hag", "name": "Haggai", "testament": "O", "start": "hag"},
  {"id": "Zech", "name": "Zechariah", "testament": "O", "start": "zec"},
  {"id": "Mal", "name": "Malachi", "testament": "O", "start": "mal"},
  {"id": "Matt", "name": "Matthew", "testament": "N", "start": "mat"},
  {"id": "Mark", "name": "Mark", "testament": "N", "start": "mar"},
  {"id": "Luke", "name": "Luke", "testament": "N", "start": "luk"},
  {"id": "John", "name": "John", "testament": "N", "start": "joh"},
  {"id": "Acts", "name": "Acts", "testament": "N", "start": "act"},
  {"id": "Rom", "name": "Romans", "testament": "N", "start": "rom"},
  {"id": "1Cor", "name": "1 Corinthians", "testament": "N", "start": "1co"},
  {"id": "2Cor", "name": "2 Corinthians", "testament": "N", "start": "2co"},
  {"id": "Gal", "name": "Galatians", "testament": "N", "start": "gal"},
  {"id": "Eph", "name": "Ephesians", "testament": "N", "start": "eph"},
  {"id": "Phil", "name": "Philippians", "testament": "N", "start": "phili"},
  {"id": "Col", "name": "Colossians", "testament": "N", "start": "col"},
  {"id": "1Thess", "name": "1 Thessalonians", "testament": "N", "start": "1th"},
  {"id": "2Thess", "name": "2 Thessalonians", "testament": "N", "start": "2th"},
  {"id": "1Tim", "name": "1 Timothy", "testament": "N", "start": "1ti"},
  {"id": "2Tim", "name": "2 Timothy", "testament": "N", "start": "2ti"},
  {"id": "Titus", "name": "Titus", "testament": "N", "start": "tit"},
  {"id": "Phlm", "name": "Philemon", "testament": "N", "start": "phile"},
  {"id": "Heb", "name": "Hebrews", "testament": "N", "start": "heb"},
  {"id": "Jas", "name": "James", "testament": "N", "start": "jam"},
  {"id": "1Pet", "name": "1 Peter", "testament": "N", "start": "1pe"},
  {"id": "2Pet", "name": "2 Peter", "testament": "N", "start": "2pe"},
  {"id": "1John", "name": "1 John", "testament": "N", "start": "1jo"},
  {"id": "2John", "name": "2 John", "testament": "N", "start": "2jo"},
  {"id": "3John", "name": "3 John", "testament": "N", "start": "3jo"},
  {"id": "Jude", "name": "Jude", "testament": "N", "start": "jude"},
  {"id": "Rev", "name": "Revelation", "testament": "N", "start": "rev"}
];

module.exports = osisList;
